Repository makenowjust-labs/recheck, pull requests merged in 2025-03, with the labels that each got.

#1383 Ensure that checkSync() and check() do not stall without the flags parameter
  packages/recheck/src/main.ts
Labels: feature

#1402 Use React v18 for website
  renovate.json
  website/package.json
  yarn.lock
Labels: fix

#1404 Pin react-dom version
  renovate.json
Labels: misc

#1405 Update copyright year 2024 -> 2025
  LICENSE
  README.md
  website/docusaurus.config.js
Labels: misc

#1406 Drop Node v18 support
  .github/workflows/main.yml
  packages/eslint-plugin-redos/package.json
  packages/recheck/package.json
Labels: fix
